<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="jentibhai" ignored="1" name="ultimateqa_week_15" tests="1" failures="1" timestamp="2022-12-13T17:19:38 GMT" time="6.687" errors="0">
  <testcase name="verifyUserShouldNavigateToLoginPageSuccessfully" time="0.001" classname="ultimateqa.com.testsuite.LoginPageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at ultimateqa.com.testsuite.LoginPageTest.verifyUserShouldNavigateToLoginPageSuccessfully(LoginPageTest.java:19)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserShouldNavigateToLoginPageSuccessfully -->
  <testcase name="verifyTheErrorMessage" time="0.0" classname="ultimateqa.com.testsuite.LoginPageTest">
    <ignored/>
  </testcase> <!-- verifyTheErrorMessage -->
</testsuite> <!-- ultimateqa_week_15 -->
